### ISSUE TITLE
huge_tlb should not take an option.

### ISSUE THREAD

**Issue by Stargateur** [de-vri-es/mem-fd-rs#1]
it doesn't make sense to call this function with a `None`. For convenience this function could take a `Into<Option<HugeTlb>>`.

https://docs.rs/memfile/0.1.3/memfile/struct.CreateOptions.html#method.huge_tlb

**Comment by de-vri-es** [comment]
Taking an `Into<Option<HugeTlb>>` doesn't make it any more convenient, does it?

We could just drop the `Option` and add a `disable_huge_tlb()` or something, just in case some really wants to disable it after it was set.

You already noticed that the `CreateOptions` were not really designed as a builder, but really just as a way of passing in options to the constructor. But I think turning it into a builder is a good idea :)

**Comment by Stargateur** [comment]
```rust
fn foo<T: Into<Option<u32>>>(t: T) {
    println!("{:?}", t.into());
}

fn main() {
    foo(42u32);
}
```

magic of blanked implementation.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a94315b8bb59707aebb15f762626f8a9

**Comment by de-vri-es** [comment]
Oh, weird. I specifically remember that `impl` not existing, but it seems I was mistaken. Yeah, that's nicer than what I did now :)
