### ISSUE TITLE
instead of having metadata impl as_file ?

### ISSUE THREAD

**Issue by Stargateur** [de-vri-es/mem-fd-rs#6]
maybe `AsRef<File>` or just a function as_file() ?

**Comment by de-vri-es** [comment]
I did this on purpose, because I don't want to promise that the struct contains a `File` object. Also, `set_permissions` doesn't really make sense for `MemFile`.

**Comment by Stargateur** [comment]
well so it's unsound cause https://docs.rs/memfile/0.1.3/memfile/struct.MemFile.html#method.into_file

**Comment by de-vri-es** [comment]
> well so it's unsound cause https://docs.rs/memfile/0.1.3/memfile/struct.MemFile.html#method.into_file

That's not unsound. Be aware that the term "unsound" has quite specific meaning. It means that safety rules are violated, and that is not the case here.

Additionally, being convertible *into* a file doesn't promise that we hold a file internally. Any file descriptor can be moved into a `File` object. However, implementing `AsRef` or returning a reference to a `File` object requires that the lifetime of the `File` is linked to that of the `MemFile`. And that is only possible if `MemFile` wraps a `File`.

Currently, `MemFile` does contain a `File` object, but it's not a promise I want to make.
