### ISSUE TITLE
avoid allocating for the name

### ISSUE THREAD

**Issue by Stargateur** [de-vri-es/mem-fd-rs#7]
This issue is to talk about avoid allocating in sys for the name hint of the memfile.

- Use a enum instead of &str
- Use two function
- Replace &str by CStr

I think it's ok to replace by CStr, it's a type mean to do that. It's make the use a bit more difficult but user of this lib are not the common people, you don't often need to create a memfile.

The actual problem of allocating is this could make difficult for embedded system as well as implementing no_std.

**Comment by de-vri-es** [comment]
I do like the idea of having an option to avoid allocation, but I don't want to take only a `CStr`. Ease of use should not be compromised, especially when in practice it will force most users to perform the same conversion that now happens internally.

> The actual problem of allocating is this could make difficult for embedded system as well as implementing no_std.

Like I said, I like allowing to avoid allocation, but keep in mind that bare bones embedded usage isn't feasible for this crate anyway: it exposes OS functionality. Making `std` optional is also not possible for other reasons: the most important one being that the crate reports errors using `std::io::Error`.

**Comment by Stargateur** [comment]
We could expose something like that https://lib.rs/crates/cstr

well if you want to keep current &str I think have two functions is the best. Name `create_with_cstr()` ?

**Comment by de-vri-es** [comment]
Implemented in cb0b77a :)
