### ISSUE TITLE
Build failure on FreeBSD

### ISSUE THREAD

**Issue by asomers** [de-vri-es/mem-fd-rs#8]
This crate currently fails to build on FreeBSD.  Fixing it would be easy, and requires only:
* Updating the libc version after https://github.com/rust-lang/libc/pull/2465 merges
* Restricting the use of `F_SEAL_FUTURE_WRITE` to Linux only.

**Comment by de-vri-es** [comment]
Good point. Thanks for reporting it. I'll get round to this soon, or you can send a PR if you like.

If you would want to pick this up, let's just add `#[cfg(...)]` to hide the related API bits on non-Linux.

**Comment by de-vri-es** [comment]
Fixed in 827885a9ef9609d21e3dc47a856edc3dfb8d33a5 and released as 0.2.1.

I also added `cargo check` workflows for Android and FreeBSD, so it should atleast keep compiling.

Thanks again for reporting the issue!
